[project]
name = "unit-converter"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pint>=0.24.4",
    "streamlit>=1.43.2",
]
